name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cmake ..
    - name: make
      run: cd build && make -j2
    - name: make check
      run: cd build && make pytest
